Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 25
  Exclude:
    - config/environments/development.rb

Metrics/ClassLength:
  Max: 150

Metrics/LineLength: 
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - bin/bundle
